# Generated by Django 2.2 on 2020-12-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('church_city', models.CharField(max_length=255)),
                ('church_state', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('church_email', models.CharField(max_length=255)),
                ('church_phone', models.CharField(max_length=13)),
                ('denomination', models.CharField(max_length=255)),
                ('values', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('youngest', models.CharField(max_length=255)),
                ('younger', models.CharField(max_length=255)),
                ('young', models.CharField(max_length=255)),
                ('old', models.CharField(max_length=255)),
                ('oldest', models.CharField(max_length=255)),
                ('other', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=255)),
                ('user_city', models.CharField(max_length=255)),
                ('user_state', models.CharField(max_length=2)),
                ('user_email', models.CharField(max_length=255)),
                ('user_facebook', models.CharField(max_length=255)),
                ('user_instagram', models.CharField(max_length=255)),
                ('adults', models.CharField(max_length=255)),
                ('teens', models.CharField(max_length=255)),
                ('kids', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('denomination', models.CharField(max_length=255)),
                ('church_size', models.CharField(max_length=255)),
                ('student_programs', models.CharField(max_length=255)),
                ('small_groups', models.CharField(max_length=255)),
                ('user_info_other', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Img', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pic', to='church_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messsage', to='church_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='church_app.User')),
                ('wall_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_comments', to='church_app.UserMessage')),
            ],
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastor_name', models.CharField(max_length=255)),
                ('pastor_title', models.CharField(max_length=255)),
                ('pastor_phone', models.CharField(max_length=13)),
                ('pastor_email', models.CharField(max_length=255)),
                ('pastor_social', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ManyToManyField(related_name='church_pastor', to='church_app.Church')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dm', to='church_app.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_dm', to='church_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_comment', to='church_app.Church')),
                ('wall_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_post_comments', to='church_app.UserMessage')),
            ],
        ),
    ]
