# Generated by Django 2.2 on 2020-12-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_churchmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchcomments',
            name='wall_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_post_comments', to='church_app.ChurchMessage'),
        ),
    ]
