# Generated by Django 2.2 on 2020-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0004_auto_20201207_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessages',
            name='dm',
            field=models.TextField(default='DM'),
            preserve_default=False,
        ),
    ]
