# Generated by Django 2.2 on 2020-12-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0006_auto_20201208_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dm', to='church_app.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_dm', to='church_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='IndividualMessages',
        ),
    ]
